import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    // Nav / common
    dashboard: 'Dashboard', products: 'Products', cart: 'Shopping Cart',
    orders: 'My Orders', repairs: 'Repair Services', payments: 'Payments',
    profile: 'My Profile', logout: 'Logout', search: 'Search',
    addToCart: 'Add to Cart', checkout: 'Checkout', total: 'Total',
    status: 'Status', date: 'Date', actions: 'Actions', save: 'Save',
    cancel: 'Cancel', delete: 'Delete', edit: 'Edit', view: 'View',
    name: 'Name', email: 'Email', phone: 'Phone', address: 'Address',
    password: 'Password', submit: 'Submit', loading: 'Loading...',
    welcome: 'Welcome', signIn: 'Sign In', register: 'Register',
    adminDashboard: 'Admin Dashboard', users: 'Users', settings: 'Settings',
    reports: 'Reports & Analytics', inventory: 'Inventory', language: 'Language',
    messages: 'Messages', deliveryPerson: 'Delivery Person',
    // Auth
    loginTitle: 'Login to Your Account', createAccount: 'Create New Account',
    emailAddress: 'Email Address', firstName: 'First Name', lastName: 'Last Name',
    phoneNumber: 'Phone Number', registerAs: 'Register As', customer: 'Customer',
    technician: 'Technician', alreadyHaveAccount: 'Already have an account?',
    noAccount: "Don't have an account?", loginHere: 'Login here', registerHere: 'Register here',
    signingIn: 'Signing in...', creatingAccount: 'Creating account...',
    resetPassword: 'Reset Password', sendResetLink: 'Send Reset Link', backToLogin: 'Back to Login',
    checkEmail: 'Check your email for reset instructions.',
    // Dashboard
    totalOrders: 'Total Orders', pendingOrders: 'Pending Orders',
    completedOrders: 'Completed Orders', repairRequests: 'Repair Requests',
    recentOrders: 'Recent Orders', viewAll: 'View All', startShopping: 'Start shopping!',
    noOrdersYet: 'No orders yet.', browseProducts: 'Browse Products',
    accountNotVerified: 'Account not verified', completeProfile: 'Complete Profile',
    verificationPending: 'Your profile is under review.',
    verificationComplete: 'Complete your profile and submit for verification.',
    // Products
    allCategories: 'All Categories', searchProducts: 'Search products...',
    noProductsFound: 'No products found.', outOfStock: 'Out of Stock',
    lowStock: 'Low Stock', inStock: 'In Stock',
    // Cart
    cartEmpty: 'Your cart is empty', addProductsToStart: 'Add some products to get started',
    clearCart: 'Clear Cart', continueShopping: 'Continue Shopping',
    orderSummary: 'Order Summary', subtotal: 'Subtotal', shipping: 'Shipping',
    free: 'Free', proceedToCheckout: 'Proceed to Checkout', item: 'item', items: 'items',
    // Orders
    myOrders: 'My Orders', orderNumber: 'Order #', action: 'Action',
    noOrders: 'No orders yet.',
    // Repairs
    repairServices: 'Repair Services', newRequest: 'New Request',
    submitRepairRequest: 'Submit Repair Request', deviceType: 'Device Type',
    issueDescription: 'Issue Description', submitRequest: 'Submit Request',
    myRepairRequests: 'My Repair Requests', estimatedCost: 'Est. Cost',
    noRepairsYet: 'No repair requests yet.', repairSubmitted: 'Repair request submitted!',
    // Payments
    myPayments: 'My Payments', paymentHistory: 'Payment History',
    bank: 'Bank', transactionId: 'Transaction ID', noPaymentsYet: 'No payments yet.',
    awaitingSubmission: 'Awaiting submission',
    // Profile
    myProfile: 'My Profile', accountVerified: 'Account Verified',
    verificationPendingStatus: 'Verification Pending', verificationRejected: 'Verification Rejected',
    completeProfileToVerify: 'Complete your profile to get verified:',
    uploadProfilePicture: 'Upload a profile picture',
    enterNationalId: 'Enter your National ID or FAN number',
    addPhoneNumber: 'Add your phone number',
    nameAndEmail: 'Name & Email', updateName: 'Update Name',
    contactAdminEmail: 'Contact admin to change email',
    changePassword: 'Change Password', currentPassword: 'Current Password',
    newPassword: 'New Password', confirmNewPassword: 'Confirm New Password',
    identityVerification: 'Identity Verification', nationalIdNumber: 'National ID Number',
    fanNumber: 'FAN Number (alternative)', uploadIdDocument: 'Upload ID Document',
    saveAndSubmit: 'Save & Submit for Verification', submitting: 'Submitting...',
    awaitingReview: 'Awaiting admin review...', verifiedInfo: 'Verified Information',
    contactAdmin: 'Contact Admin', fullAccessVerified: 'Your identity has been verified.',
    // Checkout
    completeYourOrder: 'Complete Your Order', shippingAndPayment: 'Shipping & Payment',
    shippingAddress: 'Shipping Address', paymentMethod: 'Payment Method',
    selectBank: 'Select bank', placingOrder: 'Placing Order...', placeOrder: 'Place Order',
    submitPaymentProof: 'Submit Payment Proof', bankTransferDetails: 'Bank Transfer Details',
    accountNumber: 'Account Number', accountName: 'Account Name', amount: 'Amount',
    transferExactAmount: 'Transfer the exact amount then fill in the details below.',
    paymentConfirmation: 'Payment Confirmation', transactionRef: 'Transaction ID / Reference Number',
    uploadReceipt: 'Upload Receipt (optional)', submittingPayment: 'Submitting...',
    submitProof: 'Submit Payment Proof', paymentProofSubmitted: 'Payment proof submitted!',
    // Admin
    usersManagement: 'Users Management', addUser: 'Add User', addNewUser: 'Add New User',
    userVerification: 'User Verification', verifyUser: 'Verify User', reject: 'Reject',
    revokeVerification: 'Revoke Verification', searchUsers: 'Search users...',
    role: 'Role', verification: 'Verification', active: 'Active', inactive: 'Inactive',
    verified: 'Verified', pending: 'Pending', unverified: 'Unverified',
    enable: 'Enable', disable: 'Disable', creating: 'Creating...', createUser: 'Create User',
    productsManagement: 'Products Management', addProduct: 'Add Product',
    editProduct: 'Edit Product', addNewProduct: 'Add New Product',
    totalProducts: 'Total Products', lowStockCount: 'Low Stock', outOfStockCount: 'Out of Stock',
    productName: 'Product Name', price: 'Price', stockQuantity: 'Stock Quantity',
    category: 'Category', brand: 'Brand', sku: 'SKU', description: 'Description',
    featured: 'Featured', saving: 'Saving...', updateProduct: 'Update Product',
    noProductsFound2: 'No products found.',
    ordersManagement: 'Orders Management', customerLabel: 'Customer', updateStatus: 'Update Status',
    noOrdersFound: 'No orders found.',
    repairRequestsTitle: 'Repair Requests', issue: 'Issue', technicianLabel: 'Technician',
    unassigned: 'Unassigned', noRepairRequests: 'No repair requests.',
    paymentsVerification: 'Payments Verification', all: 'All', approved: 'Approved',
    rejected: 'Rejected', order: 'Order', receipt: 'Receipt', noReceipt: 'No receipt',
    noPaymentsFound: 'No payments found.',
    reportsAnalytics: 'Reports & Analytics', totalRevenue: 'Total Revenue',
    totalUsers: 'Total Users', revenueLastMonths: 'Revenue (Last 6 Months)',
    ordersLastMonths: 'Orders (Last 6 Months)', dailyRevenue: 'Daily Revenue (Last 7 Days)',
    topProducts: 'Top 5 Products by Sales', ordersByStatus: 'Orders by Status',
    usersByRole: 'Users by Role', repairsByStatus: 'Repairs by Status',
    paymentMethodsSummary: 'Payment Methods Summary', transactions: 'Transactions',
    inventoryTitle: 'Inventory', manageProducts: 'Manage Products',
    needsRestocking: 'product(s) need restocking.',
    bankSettings: 'Bank Settings', bankSettingsDesc: 'Manage bank accounts shown to customers during checkout.',
    bankName: 'Bank Name', saveChanges: 'Save', addAccount: 'Add Account',
    adminProfile: 'Admin Profile', updateProfile: 'Update Profile',
    administrator: 'Administrator',
    // Technician
    techDashboard: 'Technician Dashboard', myAssigned: 'My Assigned',
    inProgress: 'In Progress', completed: 'Completed',
    readyToWork: 'Ready to work?', viewRepairs: 'View Repairs',
    viewAndManageRepairs: 'View and manage your repair assignments',
    repairAssignments: 'Repair Assignments', availableRepairs: 'Available Repairs',
    myRepairs: 'My Repairs', claim: 'Claim', notes: 'Notes',
    noRepairsAssigned: 'No repairs assigned yet. Claim one above.',
    // Sidebar labels
    shoppingCart: 'Shopping Cart', repairServices2: 'Repair Services',
    usersManagementSidebar: 'Users Management', productsManagementSidebar: 'Products Management',
    ordersManagementSidebar: 'Orders Management', paymentsVerificationSidebar: 'Payments Verification',
    repairRequestsSidebar: 'Repair Requests', bankSettingsSidebar: 'Bank Settings',
    repairAssignmentsSidebar: 'Repair Assignments',
  },
  om: {
    // Nav / common
    dashboard: 'Gabatee', products: 'Meeshaalee', cart: 'Kuusaa Bitaa',
    orders: 'Ajajawwan Koo', repairs: 'Tajaajila Suphaa', payments: 'Kafaltii',
    profile: 'Profaayilii Koo', logout: 'Ba\'i', search: 'Barbaadi',
    addToCart: 'Kuusaatti Ida\'i', checkout: 'Kafali', total: 'Waliigala',
    status: 'Haala', date: 'Guyyaa', actions: 'Tarkaanfii', save: 'Kuusi',
    cancel: 'Dhiisi', delete: 'Haqi', edit: 'Gulaali', view: 'Ilaali',
    name: 'Maqaa', email: 'Imeelii', phone: 'Bilbila', address: 'Teessoo',
    password: 'Jecha Darbii', submit: 'Ergi', loading: 'Eegaa...',
    welcome: 'Baga Nagaan Dhuftan', signIn: 'Seeni', register: 'Galmeessi',
    adminDashboard: 'Gabatee Bulchiinsaa', users: 'Fayyadamtoota', settings: 'Qindaa\'ina',
    reports: 'Gabaasaa fi Xiinxala', inventory: 'Kuusaa', language: 'Afaan',
    messages: 'Ergaalee', deliveryPerson: 'Nama Geejjibaa',
    // Auth
    loginTitle: 'Herrega Kee Seeni', createAccount: 'Herrega Haaraa Bani',
    emailAddress: 'Teessoo Imeelii', firstName: 'Maqaa Duraa', lastName: 'Maqaa Maatii',
    phoneNumber: 'Lakkoofsa Bilbilaa', registerAs: 'Akka Meeqa Galmeessi', customer: 'Bitaa',
    technician: 'Teekniishiyaanii', alreadyHaveAccount: 'Herrega qabdaa?',
    noAccount: 'Herrega hin qabduu?', loginHere: 'Asitti Seeni', registerHere: 'Asitti Galmeessi',
    signingIn: 'Seenaa jira...', creatingAccount: 'Herrega banaa jira...',
    resetPassword: 'Jecha Darbii Haaromsi', sendResetLink: 'Hidhaa Ergi', backToLogin: 'Gara Seensaatti Deebi\'i',
    checkEmail: 'Imeelii kee ilaali.',
    // Dashboard
    totalOrders: 'Ajajawwan Waliigalaa', pendingOrders: 'Ajajawwan Eegaa Jiran',
    completedOrders: 'Ajajawwan Xumuramanii', repairRequests: 'Gaaffii Suphaa',
    recentOrders: 'Ajajawwan Dhiyoo', viewAll: 'Hunda Ilaali', startShopping: 'Bituu Jalqabi!',
    noOrdersYet: 'Ajajni hin jiru.', browseProducts: 'Meeshaalee Ilaali',
    accountNotVerified: 'Herreegni hin mirkanaafamne', completeProfile: 'Profaayilii Guuti',
    verificationPending: 'Profaayilin kee ilaalama jira.',
    verificationComplete: 'Profaayilii guutii mirkanaa\'ina gaafadhu.',
    // Products
    allCategories: 'Gosa Hunda', searchProducts: 'Meeshaalee Barbaadi...',
    noProductsFound: 'Meeshaan hin argamne.', outOfStock: 'Kuusaa Dhumee',
    lowStock: 'Kuusaan Xiqqaa', inStock: 'Kuusaa Jira',
    // Cart
    cartEmpty: 'Kuusaan kee duwwaa dha', addProductsToStart: 'Meeshaalee itti ida\'i',
    clearCart: 'Kuusaa Haqii', continueShopping: 'Bituu Itti Fufi',
    orderSummary: 'Cuunfaa Ajajaa', subtotal: 'Walakkaa', shipping: 'Ergaa',
    free: 'Bilisaan', proceedToCheckout: 'Gara Kafaltiitti Darbi', item: 'meeshaa', items: 'meeshaalee',
    // Orders
    myOrders: 'Ajajawwan Koo', orderNumber: 'Ajaja #', action: 'Tarkaanfii',
    noOrders: 'Ajajni hin jiru.',
    // Repairs
    repairServices: 'Tajaajila Suphaa', newRequest: 'Gaaffii Haaraa',
    submitRepairRequest: 'Gaaffii Suphaa Ergi', deviceType: 'Gosa Meeshaa',
    issueDescription: 'Rakkoo Ibsi', submitRequest: 'Gaaffii Ergi',
    myRepairRequests: 'Gaaffii Suphaa Koo', estimatedCost: 'Gatii Tilmaamaa',
    noRepairsYet: 'Gaaffiin suphaa hin jiru.', repairSubmitted: 'Gaaffiin suphaa ergame!',
    // Payments
    myPayments: 'Kafaltii Koo', paymentHistory: 'Seenaa Kafaltii',
    bank: 'Baankii', transactionId: 'ID Hojii', noPaymentsYet: 'Kafaltiin hin jiru.',
    awaitingSubmission: 'Ergaa eegaa jira',
    // Profile
    myProfile: 'Profaayilii Koo', accountVerified: 'Herreegni Mirkanaafame',
    verificationPendingStatus: 'Mirkanaa\'inni Eegaa Jira', verificationRejected: 'Mirkanaa\'inni Dideera',
    completeProfileToVerify: 'Profaayilii guutii mirkanaa\'ina gaafadhu:',
    uploadProfilePicture: 'Suuraa profaayilii fe\'i',
    enterNationalId: 'ID Biyyaa ykn lakkoofsa FAN galchi',
    addPhoneNumber: 'Lakkoofsa bilbilaa itti ida\'i',
    nameAndEmail: 'Maqaa fi Imeelii', updateName: 'Maqaa Haaromsi',
    contactAdminEmail: 'Imeelii jijjiiruf bulchiinsa quunnamii',
    changePassword: 'Jecha Darbii Jijjiiri', currentPassword: 'Jecha Darbii Ammaa',
    newPassword: 'Jecha Darbii Haaraa', confirmNewPassword: 'Jecha Darbii Haaraa Mirkaneessi',
    identityVerification: 'Eenyummaa Mirkanaa\'ina', nationalIdNumber: 'Lakkoofsa ID Biyyaa',
    fanNumber: 'Lakkoofsa FAN (filannoo)', uploadIdDocument: 'Galmee ID Fe\'i',
    saveAndSubmit: 'Kuusi fi Mirkanaa\'inaaf Ergi', submitting: 'Ergaa jira...',
    awaitingReview: 'Bulchiinsi ilaalaa jira...', verifiedInfo: 'Odeeffannoo Mirkanaafame',
    contactAdmin: 'Bulchiinsa Quunnamii', fullAccessVerified: 'Eenyummaan kee mirkanaafame.',
    // Checkout
    completeYourOrder: 'Ajaja Kee Xumurii', shippingAndPayment: 'Ergaa fi Kafaltii',
    shippingAddress: 'Teessoo Ergaa', paymentMethod: 'Mala Kafaltii',
    selectBank: 'Baankii Filadhu', placingOrder: 'Ajaja Kaa\'aa jira...', placeOrder: 'Ajaja Kaa\'i',
    submitPaymentProof: 'Ragaa Kafaltii Ergi', bankTransferDetails: 'Odeeffannoo Jijjiira Baankii',
    accountNumber: 'Lakkoofsa Herreegaa', accountName: 'Maqaa Herreegaa', amount: 'Gatii',
    transferExactAmount: 'Gatii sirrii ergii ergaa gadii guuti.',
    paymentConfirmation: 'Mirkaneessa Kafaltii', transactionRef: 'ID / Lakkoofsa Wabii',
    uploadReceipt: 'Rasiidhii Fe\'i (dirqama miti)', submittingPayment: 'Ergaa jira...',
    submitProof: 'Ragaa Kafaltii Ergi', paymentProofSubmitted: 'Ragaan kafaltii ergame!',
    // Admin
    usersManagement: 'Bulchiinsa Fayyadamtoota', addUser: 'Fayyadamaa Ida\'i', addNewUser: 'Fayyadamaa Haaraa Ida\'i',
    userVerification: 'Mirkanaa\'ina Fayyadamaa', verifyUser: 'Fayyadamaa Mirkaneessi', reject: 'Didi',
    revokeVerification: 'Mirkanaa\'ina Haqii', searchUsers: 'Fayyadamtoota Barbaadi...',
    role: 'Gahee', verification: 'Mirkanaa\'ina', active: 'Hojjataa', inactive: 'Hojjachaa Hin Jirre',
    verified: 'Mirkanaafame', pending: 'Eegaa Jira', unverified: 'Hin Mirkanaafamne',
    enable: 'Hoji Jalqabi', disable: 'Dhaabi', creating: 'Uumaa jira...', createUser: 'Fayyadamaa Uumi',
    productsManagement: 'Bulchiinsa Meeshaalee', addProduct: 'Meeshaa Ida\'i',
    editProduct: 'Meeshaa Gulaali', addNewProduct: 'Meeshaa Haaraa Ida\'i',
    totalProducts: 'Meeshaalee Waliigalaa', lowStockCount: 'Kuusaan Xiqqaa', outOfStockCount: 'Kuusaa Dhumee',
    productName: 'Maqaa Meeshaa', price: 'Gatii', stockQuantity: 'Baay\'ina Kuusaa',
    category: 'Gosa', brand: 'Mallattoo', sku: 'SKU', description: 'Ibsa',
    featured: 'Filatamaa', saving: 'Kuusaa jira...', updateProduct: 'Meeshaa Haaromsi',
    noProductsFound2: 'Meeshaan hin argamne.',
    ordersManagement: 'Bulchiinsa Ajajawwanii', customerLabel: 'Bitaa', updateStatus: 'Haala Haaromsi',
    noOrdersFound: 'Ajajni hin argamne.',
    repairRequestsTitle: 'Gaaffii Suphaa', issue: 'Rakkoo', technicianLabel: 'Teekniishiyaanii',
    unassigned: 'Hin Ramadamne', noRepairRequests: 'Gaaffiin suphaa hin jiru.',
    paymentsVerification: 'Mirkanaa\'ina Kafaltii', all: 'Hunda', approved: 'Hayyamame',
    rejected: 'Dideera', order: 'Ajaja', receipt: 'Rasiidhii', noReceipt: 'Rasiidhii hin jiru',
    noPaymentsFound: 'Kafaltiin hin argamne.',
    reportsAnalytics: 'Gabaasaa fi Xiinxala', totalRevenue: 'Galii Waliigalaa',
    totalUsers: 'Fayyadamtoota Waliigalaa', revenueLastMonths: 'Galii (Ji\'oota 6 Darban)',
    ordersLastMonths: 'Ajajawwan (Ji\'oota 6 Darban)', dailyRevenue: 'Galii Guyyaa (Guyyoota 7 Darban)',
    topProducts: 'Meeshaalee 5 Gurguramoo', ordersByStatus: 'Ajajawwan Haala Isaaniin',
    usersByRole: 'Fayyadamtoota Gahee Isaaniin', repairsByStatus: 'Suphaa Haala Isaaniin',
    paymentMethodsSummary: 'Cuunfaa Mala Kafaltii', transactions: 'Hojii',
    inventoryTitle: 'Kuusaa', manageProducts: 'Meeshaalee Bulchi',
    needsRestocking: 'meeshaan(oonni) kuusaa barbaadu.',
    bankSettings: 'Qindaa\'ina Baankii', bankSettingsDesc: 'Herreega baankii bittoota argisiisu bulchi.',
    bankName: 'Maqaa Baankii', saveChanges: 'Kuusi', addAccount: 'Herreega Ida\'i',
    adminProfile: 'Profaayilii Bulchiinsaa', updateProfile: 'Profaayilii Haaromsi',
    administrator: 'Bulchiinsaa',
    // Technician
    techDashboard: 'Gabatee Teekniishiyaanii', myAssigned: 'Kan Naaf Ramadame',
    inProgress: 'Hojjatamaa Jira', completed: 'Xumurame',
    readyToWork: 'Hojjachuuf qophii?', viewRepairs: 'Suphaa Ilaali',
    viewAndManageRepairs: 'Ramaddii suphaa kee ilaali fi bulchi',
    repairAssignments: 'Ramaddii Suphaa', availableRepairs: 'Suphaa Argamuu Danda\'an',
    myRepairs: 'Suphaa Koo', claim: 'Fudhuu', notes: 'Yaadannoo',
    noRepairsAssigned: 'Suphaan hin ramadamne. Tokko fudhuu.',
    // Sidebar
    shoppingCart: 'Kuusaa Bitaa', repairServices2: 'Tajaajila Suphaa',
    usersManagementSidebar: 'Bulchiinsa Fayyadamtoota', productsManagementSidebar: 'Bulchiinsa Meeshaalee',
    ordersManagementSidebar: 'Bulchiinsa Ajajawwanii', paymentsVerificationSidebar: 'Mirkanaa\'ina Kafaltii',
    repairRequestsSidebar: 'Gaaffii Suphaa', bankSettingsSidebar: 'Qindaa\'ina Baankii',
    repairAssignmentsSidebar: 'Ramaddii Suphaa',
  },
  am: {
    // Nav / common
    dashboard: 'ዳሽቦርድ', products: 'ምርቶች', cart: 'የግዢ ጋሪ',
    orders: 'ትዕዛዞቼ', repairs: 'የጥገና አገልግሎት', payments: 'ክፍያዎች',
    profile: 'መገለጫዬ', logout: 'ውጣ', search: 'ፈልግ',
    addToCart: 'ወደ ጋሪ ጨምር', checkout: 'ክፈል', total: 'ጠቅላላ',
    status: 'ሁኔታ', date: 'ቀን', actions: 'ድርጊቶች', save: 'አስቀምጥ',
    cancel: 'ሰርዝ', delete: 'ሰርዝ', edit: 'አርትዕ', view: 'ይመልከቱ',
    name: 'ስም', email: 'ኢሜይል', phone: 'ስልክ', address: 'አድራሻ',
    password: 'የይለፍ ቃል', submit: 'አስገባ', loading: 'በመጫን ላይ...',
    welcome: 'እንኳን ደህና መጡ', signIn: 'ግባ', register: 'ተመዝገብ',
    adminDashboard: 'የአስተዳዳሪ ዳሽቦርድ', users: 'ተጠቃሚዎች', settings: 'ቅንብሮች',
    reports: 'ሪፖርቶች እና ትንታኔ', inventory: 'ክምችት', language: 'ቋንቋ',
    messages: 'መልዕክቶች', deliveryPerson: 'አቅራቢ',
    // Auth
    loginTitle: 'ወደ መለያዎ ይግቡ', createAccount: 'አዲስ መለያ ይፍጠሩ',
    emailAddress: 'የኢሜይል አድራሻ', firstName: 'የመጀመሪያ ስም', lastName: 'የአባት ስም',
    phoneNumber: 'የስልክ ቁጥር', registerAs: 'እንደ ምን ይመዝገቡ', customer: 'ደንበኛ',
    technician: 'ቴክኒሻን', alreadyHaveAccount: 'መለያ አለዎት?',
    noAccount: 'መለያ የለዎትም?', loginHere: 'እዚህ ይግቡ', registerHere: 'እዚህ ይመዝገቡ',
    signingIn: 'በመግባት ላይ...', creatingAccount: 'መለያ በመፍጠር ላይ...',
    resetPassword: 'የይለፍ ቃል ዳግም ያስጀምሩ', sendResetLink: 'ማስጀመሪያ ሊንክ ላክ', backToLogin: 'ወደ ግቤት ተመለስ',
    checkEmail: 'ኢሜይልዎን ያረጋግጡ።',
    // Dashboard
    totalOrders: 'ጠቅላላ ትዕዛዞች', pendingOrders: 'በመጠባበቅ ላይ ያሉ ትዕዛዞች',
    completedOrders: 'የተጠናቀቁ ትዕዛዞች', repairRequests: 'የጥገና ጥያቄዎች',
    recentOrders: 'የቅርብ ጊዜ ትዕዛዞች', viewAll: 'ሁሉንም ይመልከቱ', startShopping: 'ግዢ ይጀምሩ!',
    noOrdersYet: 'ምንም ትዕዛዝ የለም።', browseProducts: 'ምርቶችን ያስሱ',
    accountNotVerified: 'መለያ አልተረጋገጠም', completeProfile: 'መገለጫ ያጠናቅቁ',
    verificationPending: 'መገለጫዎ በግምገማ ላይ ነው።',
    verificationComplete: 'ለማረጋገጥ መገለጫዎን ያጠናቅቁ።',
    // Products
    allCategories: 'ሁሉም ምድቦች', searchProducts: 'ምርቶችን ፈልግ...',
    noProductsFound: 'ምንም ምርት አልተገኘም።', outOfStock: 'ክምችት አልቋል',
    lowStock: 'ዝቅተኛ ክምችት', inStock: 'ክምችት አለ',
    // Cart
    cartEmpty: 'ጋሪዎ ባዶ ነው', addProductsToStart: 'ምርቶችን ጨምሩ',
    clearCart: 'ጋሪ አጽዳ', continueShopping: 'ግዢ ቀጥሉ',
    orderSummary: 'የትዕዛዝ ማጠቃለያ', subtotal: 'ንዑስ ድምር', shipping: 'ማጓጓዣ',
    free: 'ነፃ', proceedToCheckout: 'ወደ ክፍያ ቀጥሉ', item: 'ዕቃ', items: 'ዕቃዎች',
    // Orders
    myOrders: 'ትዕዛዞቼ', orderNumber: 'ትዕዛዝ #', action: 'ድርጊት',
    noOrders: 'ምንም ትዕዛዝ የለም።',
    // Repairs
    repairServices: 'የጥገና አገልግሎት', newRequest: 'አዲስ ጥያቄ',
    submitRepairRequest: 'የጥገና ጥያቄ ያስገቡ', deviceType: 'የመሳሪያ ዓይነት',
    issueDescription: 'ችግሩን ይግለጹ', submitRequest: 'ጥያቄ ያስገቡ',
    myRepairRequests: 'የጥገና ጥያቄዎቼ', estimatedCost: 'የተገመተ ወጪ',
    noRepairsYet: 'ምንም የጥገና ጥያቄ የለም።', repairSubmitted: 'የጥገና ጥያቄ ተልኳል!',
    // Payments
    myPayments: 'ክፍያዎቼ', paymentHistory: 'የክፍያ ታሪክ',
    bank: 'ባንክ', transactionId: 'የግብይት መለያ', noPaymentsYet: 'ምንም ክፍያ የለም።',
    awaitingSubmission: 'ማስገቢያ በመጠባበቅ ላይ',
    // Profile
    myProfile: 'መገለጫዬ', accountVerified: 'መለያ ተረጋግጧል',
    verificationPendingStatus: 'ማረጋገጫ በመጠባበቅ ላይ', verificationRejected: 'ማረጋገጫ ተቀባይነት አላገኘም',
    completeProfileToVerify: 'ለማረጋገጥ መገለጫዎን ያጠናቅቁ:',
    uploadProfilePicture: 'የፕሮፋይል ፎቶ ይጫኑ',
    enterNationalId: 'ብሔራዊ መታወቂያ ወይም FAN ቁጥር ያስገቡ',
    addPhoneNumber: 'የስልክ ቁጥር ያስገቡ',
    nameAndEmail: 'ስም እና ኢሜይል', updateName: 'ስም ያዘምኑ',
    contactAdminEmail: 'ኢሜይል ለመቀየር አስተዳዳሪን ያነጋግሩ',
    changePassword: 'የይለፍ ቃል ይቀይሩ', currentPassword: 'የአሁኑ የይለፍ ቃል',
    newPassword: 'አዲስ የይለፍ ቃል', confirmNewPassword: 'አዲስ የይለፍ ቃል ያረጋግጡ',
    identityVerification: 'የማንነት ማረጋገጫ', nationalIdNumber: 'ብሔራዊ መታወቂያ ቁጥር',
    fanNumber: 'FAN ቁጥር (አማራጭ)', uploadIdDocument: 'የመታወቂያ ሰነድ ይጫኑ',
    saveAndSubmit: 'አስቀምጥ እና ለማረጋገጥ ያስገቡ', submitting: 'በማስገባት ላይ...',
    awaitingReview: 'አስተዳዳሪ እየገመገመ ነው...', verifiedInfo: 'የተረጋገጠ መረጃ',
    contactAdmin: 'አስተዳዳሪን ያነጋግሩ', fullAccessVerified: 'ማንነትዎ ተረጋግጧል።',
    // Checkout
    completeYourOrder: 'ትዕዛዝዎን ያጠናቅቁ', shippingAndPayment: 'ማጓጓዣ እና ክፍያ',
    shippingAddress: 'የማጓጓዣ አድራሻ', paymentMethod: 'የክፍያ ዘዴ',
    selectBank: 'ባንክ ይምረጡ', placingOrder: 'ትዕዛዝ በማስቀመጥ ላይ...', placeOrder: 'ትዕዛዝ ያስቀምጡ',
    submitPaymentProof: 'የክፍያ ማስረጃ ያስገቡ', bankTransferDetails: 'የባንክ ዝውውር ዝርዝሮች',
    accountNumber: 'የሂሳብ ቁጥር', accountName: 'የሂሳብ ስም', amount: 'መጠን',
    transferExactAmount: 'ትክክለኛውን መጠን ያስተላልፉ ከዚያ ዝርዝሮቹን ይሙሉ።',
    paymentConfirmation: 'የክፍያ ማረጋገጫ', transactionRef: 'የግብይት መለያ / ማጣቀሻ ቁጥር',
    uploadReceipt: 'ደረሰኝ ይጫኑ (አማራጭ)', submittingPayment: 'በማስገባት ላይ...',
    submitProof: 'የክፍያ ማስረጃ ያስገቡ', paymentProofSubmitted: 'የክፍያ ማስረጃ ተልኳል!',
    // Admin
    usersManagement: 'የተጠቃሚዎች አስተዳደር', addUser: 'ተጠቃሚ ጨምር', addNewUser: 'አዲስ ተጠቃሚ ጨምር',
    userVerification: 'የተጠቃሚ ማረጋገጫ', verifyUser: 'ተጠቃሚ ያረጋግጡ', reject: 'ውድቅ ያድርጉ',
    revokeVerification: 'ማረጋገጫ ሰርዝ', searchUsers: 'ተጠቃሚዎችን ፈልግ...',
    role: 'ሚና', verification: 'ማረጋገጫ', active: 'ንቁ', inactive: 'ንቁ ያልሆነ',
    verified: 'ተረጋግጧል', pending: 'በመጠባበቅ ላይ', unverified: 'አልተረጋገጠም',
    enable: 'አንቃ', disable: 'አሰናክል', creating: 'በመፍጠር ላይ...', createUser: 'ተጠቃሚ ፍጠር',
    productsManagement: 'የምርቶች አስተዳደር', addProduct: 'ምርት ጨምር',
    editProduct: 'ምርት አርትዕ', addNewProduct: 'አዲስ ምርት ጨምር',
    totalProducts: 'ጠቅላላ ምርቶች', lowStockCount: 'ዝቅተኛ ክምችት', outOfStockCount: 'ክምችት አልቋል',
    productName: 'የምርት ስም', price: 'ዋጋ', stockQuantity: 'የክምችት መጠን',
    category: 'ምድብ', brand: 'ብራንድ', sku: 'SKU', description: 'መግለጫ',
    featured: 'ተለይቶ የቀረበ', saving: 'በማስቀመጥ ላይ...', updateProduct: 'ምርት ያዘምኑ',
    noProductsFound2: 'ምንም ምርት አልተገኘም።',
    ordersManagement: 'የትዕዛዞች አስተዳደር', customerLabel: 'ደንበኛ', updateStatus: 'ሁኔታ ያዘምኑ',
    noOrdersFound: 'ምንም ትዕዛዝ አልተገኘም።',
    repairRequestsTitle: 'የጥገና ጥያቄዎች', issue: 'ችግር', technicianLabel: 'ቴክኒሻን',
    unassigned: 'ያልተመደበ', noRepairRequests: 'ምንም የጥገና ጥያቄ የለም።',
    paymentsVerification: 'የክፍያ ማረጋገጫ', all: 'ሁሉም', approved: 'ጸድቋል',
    rejected: 'ውድቅ ሆኗል', order: 'ትዕዛዝ', receipt: 'ደረሰኝ', noReceipt: 'ደረሰኝ የለም',
    noPaymentsFound: 'ምንም ክፍያ አልተገኘም።',
    reportsAnalytics: 'ሪፖርቶች እና ትንታኔ', totalRevenue: 'ጠቅላላ ገቢ',
    totalUsers: 'ጠቅላላ ተጠቃሚዎች', revenueLastMonths: 'ገቢ (ባለፉት 6 ወራት)',
    ordersLastMonths: 'ትዕዛዞች (ባለፉት 6 ወራት)', dailyRevenue: 'ዕለታዊ ገቢ (ባለፉት 7 ቀናት)',
    topProducts: 'ምርጥ 5 ምርቶች በሽያጭ', ordersByStatus: 'ትዕዛዞች በሁኔታ',
    usersByRole: 'ተጠቃሚዎች በሚና', repairsByStatus: 'ጥገናዎች በሁኔታ',
    paymentMethodsSummary: 'የክፍያ ዘዴዎች ማጠቃለያ', transactions: 'ግብይቶች',
    inventoryTitle: 'ክምችት', manageProducts: 'ምርቶችን ያስተዳድሩ',
    needsRestocking: 'ምርት(ቶች) ክምችት ያስፈልጋቸዋል።',
    bankSettings: 'የባንክ ቅንብሮች', bankSettingsDesc: 'ለደንበኞች በክፍያ ጊዜ የሚታዩ የባንክ ሂሳቦችን ያስተዳድሩ።',
    bankName: 'የባንክ ስም', saveChanges: 'አስቀምጥ', addAccount: 'ሂሳብ ጨምር',
    adminProfile: 'የአስተዳዳሪ መገለጫ', updateProfile: 'መገለጫ ያዘምኑ',
    administrator: 'አስተዳዳሪ',
    // Technician
    techDashboard: 'የቴክኒሻን ዳሽቦርድ', myAssigned: 'የተመደቡልኝ',
    inProgress: 'በሂደት ላይ', completed: 'ተጠናቋል',
    readyToWork: 'ለመስራት ዝግጁ?', viewRepairs: 'ጥገናዎችን ይመልከቱ',
    viewAndManageRepairs: 'የጥገና ምደባዎችዎን ይመልከቱ እና ያስተዳድሩ',
    repairAssignments: 'የጥገና ምደባዎች', availableRepairs: 'ያሉ ጥገናዎች',
    myRepairs: 'ጥገናዎቼ', claim: 'ተቀበል', notes: 'ማስታወሻዎች',
    noRepairsAssigned: 'ምንም ጥገና አልተመደበም። ከላይ ይቀበሉ።',
    // Sidebar
    shoppingCart: 'የግዢ ጋሪ', repairServices2: 'የጥገና አገልግሎት',
    usersManagementSidebar: 'የተጠቃሚዎች አስተዳደር', productsManagementSidebar: 'የምርቶች አስተዳደር',
    ordersManagementSidebar: 'የትዕዛዞች አስተዳደር', paymentsVerificationSidebar: 'የክፍያ ማረጋገጫ',
    repairRequestsSidebar: 'የጥገና ጥያቄዎች', bankSettingsSidebar: 'የባንክ ቅንብሮች',
    repairAssignmentsSidebar: 'የጥገና ምደባዎች',
  }
}

const LanguageContext = createContext({})
export const useLanguage = () => useContext(LanguageContext)

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en')

  const switchLang = (l) => {
    setLang(l)
    localStorage.setItem('lang', l)
  }

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
